<?php

use Illuminate\Database\Seeder;

class CommunesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('communes')->insert([
            ['id' => 1, "name" => 'Iquique', 'province_id' => '3'],
            ['id' => 2, "name" => 'Alto Hospicio', 'province_id' => '3'],
            ['id' => 3, "name" => 'Pozo Almonte', 'province_id' => '4'],
            ['id' => 4, "name" => 'Camiña', 'province_id' => '4'],
            ['id' => 5, "name" => 'Colchane', 'province_id' => '4'],
            ['id' => 6, "name" => 'Huara', 'province_id' => '4'],
            ['id' => 7, "name" => 'Pica', 'province_id' => '4'],
            ['id' => 8, "name" => 'Antofagasta', 'province_id' => '5'],
            ['id' => 9, "name" => 'Mejillones', 'province_id' => '5'],
            ['id' => 10, "name" => 'Sierra Gorda', 'province_id' => '5'],
            ['id' => 11, "name" => 'Taltal', 'province_id' => '5'],
            ['id' => 12, "name" => 'Calama', 'province_id' => '6'],
            ['id' => 13, "name" => 'Ollagüe', 'province_id' => '6'],
            ['id' => 14, "name" => 'San Pedro de Atacama', 'province_id' => '6'],
            ['id' => 15, "name" => 'Tocopilla', 'province_id' => '7'],
            ['id' => 16, "name" => 'María Elena', 'province_id' => '7'],
            ['id' => 17, "name" => 'Copiapó', 'province_id' => '8'],
            ['id' => 18, "name" => 'Caldera', 'province_id' => '8'],
            ['id' => 19, "name" => 'Tierra Amarilla', 'province_id' => '8'],
            ['id' => 20, "name" => 'Chañaral', 'province_id' => '9'],
            ['id' => 21, "name" => 'Diego de Almagro', 'province_id' => '9'],
            ['id' => 22, "name" => 'Vallenar', 'province_id' => '10'],
            ['id' => 23, "name" => 'Alto del Carmen', 'province_id' => '10'],
            ['id' => 24, "name" => 'Freirina', 'province_id' => '10'],
            ['id' => 25, "name" => 'Huasco', 'province_id' => '10'],
            ['id' => 26, "name" => 'La Serena', 'province_id' => '11'],
            ['id' => 27, "name" => 'Coquimbo', 'province_id' => '11'],
            ['id' => 28, "name" => 'Andacollo', 'province_id' => '11'],
            ['id' => 29, "name" => 'La Higuera', 'province_id' => '11'],
            ['id' => 30, "name" => 'Paihuano', 'province_id' => '11'],
            ['id' => 31, "name" => 'Vicuña', 'province_id' => '11'],
            ['id' => 32, "name" => 'Illapel', 'province_id' => '12'],
            ['id' => 33, "name" => 'Canela', 'province_id' => '12'],
            ['id' => 34, "name" => 'Los Vilos', 'province_id' => '12'],
            ['id' => 35, "name" => 'Salamanca', 'province_id' => '12'],
            ['id' => 36, "name" => 'Ovalle', 'province_id' => '13'],
            ['id' => 37, "name" => 'Combarbalá', 'province_id' => '13'],
            ['id' => 38, "name" => 'Monte Patria', 'province_id' => '13'],
            ['id' => 39, "name" => 'Punitaqui', 'province_id' => '13'],
            ['id' => 40, "name" => 'Río Hurtado', 'province_id' => '13'],
            ['id' => 41, "name" => 'Valparaíso', 'province_id' => '14'],
            ['id' => 42, "name" => 'Casablanca', 'province_id' => '14'],
            ['id' => 43, "name" => 'Concón', 'province_id' => '14'],
            ['id' => 44, "name" => 'Juan Fernández', 'province_id' => '14'],
            ['id' => 45, "name" => 'Puchuncaví', 'province_id' => '14'],
            ['id' => 46, "name" => 'Quintero', 'province_id' => '14'],
            ['id' => 47, "name" => 'Viña del Mar', 'province_id' => '14'],
            ['id' => 48, "name" => 'Isla de Pascua', 'province_id' => '15'],
            ['id' => 49, "name" => 'Los Andes', 'province_id' => '16'],
            ['id' => 50, "name" => 'Calle Larga', 'province_id' => '16'],
            ['id' => 51, "name" => 'Rinconada', 'province_id' => '16'],
            ['id' => 52, "name" => 'San Esteban', 'province_id' => '16'],
            ['id' => 53, "name" => 'La Ligua', 'province_id' => '17'],
            ['id' => 54, "name" => 'Cabildo', 'province_id' => '17'],
            ['id' => 55, "name" => 'Papudo', 'province_id' => '17'],
            ['id' => 56, "name" => 'Petorca', 'province_id' => '17'],
            ['id' => 57, "name" => 'Zapallar', 'province_id' => '17'],
            ['id' => 58, "name" => 'Quillota', 'province_id' => '18'],
            ['id' => 59, "name" => 'La Calera', 'province_id' => '18'],
            ['id' => 60, "name" => 'Hijuelas', 'province_id' => '18'],
            ['id' => 61, "name" => 'La Cruz', 'province_id' => '18'],
            ['id' => 62, "name" => 'Nogales', 'province_id' => '18'],
            ['id' => 63, "name" => 'San Antonio', 'province_id' => '19'],
            ['id' => 64, "name" => 'Algarrobo', 'province_id' => '19'],
            ['id' => 65, "name" => 'Cartagena', 'province_id' => '19'],
            ['id' => 66, "name" => 'El Quisco', 'province_id' => '19'],
            ['id' => 67, "name" => 'El Tabo', 'province_id' => '19'],
            ['id' => 68, "name" => 'Santo Domingo', 'province_id' => '19'],
            ['id' => 69, "name" => 'San Felipe', 'province_id' => '20'],
            ['id' => 70, "name" => 'Catemu', 'province_id' => '20'],
            ['id' => 71, "name" => 'Llay Llay', 'province_id' => '20'],
            ['id' => 72, "name" => 'Panquehue', 'province_id' => '20'],
            ['id' => 73, "name" => 'Putaendo', 'province_id' => '20'],
            ['id' => 74, "name" => 'Santa María', 'province_id' => '20'],
            ['id' => 75, "name" => 'Quilpué', 'province_id' => '21'],
            ['id' => 76, "name" => 'Limache', 'province_id' => '21'],
            ['id' => 77, "name" => 'Olmué', 'province_id' => '21'],
            ['id' => 78, "name" => 'Villa Alemana', 'province_id' => '21'],
            ['id' => 79, "name" => 'Rancagua', 'province_id' => '22'],
            ['id' => 80, "name" => 'Codegua', 'province_id' => '22'],
            ['id' => 81, "name" => 'Coinco', 'province_id' => '22'],
            ['id' => 82, "name" => 'Coltauco', 'province_id' => '22'],
            ['id' => 83, "name" => 'Doñihue', 'province_id' => '22'],
            ['id' => 84, "name" => 'Graneros', 'province_id' => '22'],
            ['id' => 85, "name" => 'Las Cabras', 'province_id' => '22'],
            ['id' => 86, "name" => 'Machalí', 'province_id' => '22'],
            ['id' => 87, "name" => 'Malloa', 'province_id' => '22'],
            ['id' => 88, "name" => 'Mostazal', 'province_id' => '22'],
            ['id' => 89, "name" => 'Olivar', 'province_id' => '22'],
            ['id' => 90, "name" => 'Peumo', 'province_id' => '22'],
            ['id' => 91, "name" => 'Pichidegua', 'province_id' => '22'],
            ['id' => 92, "name" => 'Quinta de Tilcoco', 'province_id' => '22'],
            ['id' => 93, "name" => 'Rengo', 'province_id' => '22'],
            ['id' => 94, "name" => 'Requínoa', 'province_id' => '22'],
            ['id' => 95, "name" => 'San Vicente', 'province_id' => '22'],
            ['id' => 96, "name" => 'Pichilemu', 'province_id' => '23'],
            ['id' => 97, "name" => 'La Estrella', 'province_id' => '23'],
            ['id' => 98, "name" => 'Litueche', 'province_id' => '23'],
            ['id' => 99, "name" => 'Marchihue', 'province_id' => '23'],
            ['id' => 100, "name" => 'Navidad', 'province_id' => '23'],
            ['id' => 101, "name" => 'Paredones', 'province_id' => '23'],
            ['id' => 102, "name" => 'San Fernando', 'province_id' => '24'],
            ['id' => 103, "name" => 'Chépica', 'province_id' => '24'],
            ['id' => 104, "name" => 'Chimbarongo', 'province_id' => '24'],
            ['id' => 105, "name" => 'Lolol', 'province_id' => '24'],
            ['id' => 106, "name" => 'Nancagua', 'province_id' => '24'],
            ['id' => 107, "name" => 'Palmilla', 'province_id' => '24'],
            ['id' => 108, "name" => 'Peralillo', 'province_id' => '24'],
            ['id' => 109, "name" => 'Placilla', 'province_id' => '24'],
            ['id' => 110, "name" => 'Pumanque', 'province_id' => '24'],
            ['id' => 111, "name" => 'Santa Cruz', 'province_id' => '24'],
            ['id' => 112, "name" => 'Talca', 'province_id' => '25'],
            ['id' => 113, "name" => 'Constitución', 'province_id' => '25'],
            ['id' => 114, "name" => 'Curepto', 'province_id' => '25'],
            ['id' => 115, "name" => 'Empedrado', 'province_id' => '25'],
            ['id' => 116, "name" => 'Maule', 'province_id' => '25'],
            ['id' => 117, "name" => 'Pelarco', 'province_id' => '25'],
            ['id' => 118, "name" => 'Pencahue', 'province_id' => '25'],
            ['id' => 119, "name" => 'Río Claro', 'province_id' => '25'],
            ['id' => 120, "name" => 'San Clemente', 'province_id' => '25'],
            ['id' => 121, "name" => 'San Rafael', 'province_id' => '25'],
            ['id' => 122, "name" => 'Cauquenes', 'province_id' => '26'],
            ['id' => 123, "name" => 'Chanco', 'province_id' => '26'],
            ['id' => 124, "name" => 'Pelluhue', 'province_id' => '26'],
            ['id' => 125, "name" => 'Curicó', 'province_id' => '27'],
            ['id' => 126, "name" => 'Hualañé', 'province_id' => '27'],
            ['id' => 127, "name" => 'Licantén', 'province_id' => '27'],
            ['id' => 128, "name" => 'Molina', 'province_id' => '27'],
            ['id' => 129, "name" => 'Rauco', 'province_id' => '27'],
            ['id' => 130, "name" => 'Romeral', 'province_id' => '27'],
            ['id' => 131, "name" => 'Sagrada Familia', 'province_id' => '27'],
            ['id' => 132, "name" => 'Teno', 'province_id' => '27'],
            ['id' => 133, "name" => 'Vichuquén', 'province_id' => '27'],
            ['id' => 134, "name" => 'Linares', 'province_id' => '28'],
            ['id' => 135, "name" => 'Colbún', 'province_id' => '28'],
            ['id' => 136, "name" => 'Longaví', 'province_id' => '28'],
            ['id' => 137, "name" => 'Parral', 'province_id' => '28'],
            ['id' => 138, "name" => 'Retiro', 'province_id' => '28'],
            ['id' => 139, "name" => 'San Javier', 'province_id' => '28'],
            ['id' => 140, "name" => 'Villa Alegre', 'province_id' => '28'],
            ['id' => 141, "name" => 'Yerbas Buenas', 'province_id' => '28'],
            ['id' => 142, "name" => 'Concepción', 'province_id' => '29'],
            ['id' => 143, "name" => 'Coronel', 'province_id' => '29'],
            ['id' => 144, "name" => 'Chiguayante', 'province_id' => '29'],
            ['id' => 145, "name" => 'Florida', 'province_id' => '29'],
            ['id' => 146, "name" => 'Hualqui', 'province_id' => '29'],
            ['id' => 147, "name" => 'Lota', 'province_id' => '29'],
            ['id' => 148, "name" => 'Penco', 'province_id' => '29'],
            ['id' => 149, "name" => 'San Pedro de la Paz', 'province_id' => '29'],
            ['id' => 150, "name" => 'Santa Juana', 'province_id' => '29'],
            ['id' => 151, "name" => 'Talcahuano', 'province_id' => '29'],
            ['id' => 152, "name" => 'Tomé', 'province_id' => '29'],
            ['id' => 153, "name" => 'Hualpén', 'province_id' => '29'],
            ['id' => 154, "name" => 'Lebu', 'province_id' => '30'],
            ['id' => 155, "name" => 'Arauco', 'province_id' => '30'],
            ['id' => 156, "name" => 'Cañete', 'province_id' => '30'],
            ['id' => 157, "name" => 'Contulmo', 'province_id' => '30'],
            ['id' => 158, "name" => 'Curanilahue', 'province_id' => '30'],
            ['id' => 159, "name" => 'Los Álamos', 'province_id' => '30'],
            ['id' => 160, "name" => 'Tirúa', 'province_id' => '30'],
            ['id' => 161, "name" => 'Los Ángeles', 'province_id' => '31'],
            ['id' => 162, "name" => 'Antuco', 'province_id' => '31'],
            ['id' => 163, "name" => 'Cabrero', 'province_id' => '31'],
            ['id' => 164, "name" => 'Laja', 'province_id' => '31'],
            ['id' => 165, "name" => 'Mulchén', 'province_id' => '31'],
            ['id' => 166, "name" => 'Nacimiento', 'province_id' => '31'],
            ['id' => 167, "name" => 'Negrete', 'province_id' => '31'],
            ['id' => 168, "name" => 'Quilaco', 'province_id' => '31'],
            ['id' => 169, "name" => 'Quilleco', 'province_id' => '31'],
            ['id' => 170, "name" => 'San Rosendo', 'province_id' => '31'],
            ['id' => 171, "name" => 'Santa Bárbara', 'province_id' => '31'],
            ['id' => 172, "name" => 'Tucapel', 'province_id' => '31'],
            ['id' => 173, "name" => 'Yumbel', 'province_id' => '31'],
            ['id' => 174, "name" => 'Alto Biobío', 'province_id' => '31'],
            ['id' => 175, "name" => 'Chillán', 'province_id' => '32'],
            ['id' => 176, "name" => 'Bulnes', 'province_id' => '32'],
            ['id' => 177, "name" => 'Cobquecura', 'province_id' => '32'],
            ['id' => 178, "name" => 'Coelemu', 'province_id' => '32'],
            ['id' => 179, "name" => 'Coihueco', 'province_id' => '32'],
            ['id' => 180, "name" => 'Chillán Viejo', 'province_id' => '32'],
            ['id' => 181, "name" => 'El Carmen', 'province_id' => '32'],
            ['id' => 182, "name" => 'Ninhue', 'province_id' => '32'],
            ['id' => 183, "name" => 'Ñiquén', 'province_id' => '32'],
            ['id' => 184, "name" => 'Pemuco', 'province_id' => '32'],
            ['id' => 185, "name" => 'Pinto', 'province_id' => '32'],
            ['id' => 186, "name" => 'Portezuelo', 'province_id' => '32'],
            ['id' => 187, "name" => 'Quillón', 'province_id' => '32'],
            ['id' => 188, "name" => 'Quirihue', 'province_id' => '32'],
            ['id' => 189, "name" => 'Ránquil', 'province_id' => '32'],
            ['id' => 190, "name" => 'San Carlos', 'province_id' => '32'],
            ['id' => 191, "name" => 'San Fabián', 'province_id' => '32'],
            ['id' => 192, "name" => 'San Ignacio', 'province_id' => '32'],
            ['id' => 193, "name" => 'San Nicolás', 'province_id' => '32'],
            ['id' => 194, "name" => 'Treguaco', 'province_id' => '32'],
            ['id' => 195, "name" => 'Yungay', 'province_id' => '32'],
            ['id' => 196, "name" => 'Temuco', 'province_id' => '33'],
            ['id' => 197, "name" => 'Carahue', 'province_id' => '33'],
            ['id' => 198, "name" => 'Cunco', 'province_id' => '33'],
            ['id' => 199, "name" => 'Curarrehue', 'province_id' => '33'],
            ['id' => 200, "name" => 'Freire', 'province_id' => '33'],
            ['id' => 201, "name" => 'Galvarino', 'province_id' => '33'],
            ['id' => 202, "name" => 'Gorbea', 'province_id' => '33'],
            ['id' => 203, "name" => 'Lautaro', 'province_id' => '33'],
            ['id' => 204, "name" => 'Loncoche', 'province_id' => '33'],
            ['id' => 205, "name" => 'Melipeuco', 'province_id' => '33'],
            ['id' => 206, "name" => 'Nueva Imperial', 'province_id' => '33'],
            ['id' => 207, "name" => 'Padre las Casas', 'province_id' => '33'],
            ['id' => 208, "name" => 'Perquenco', 'province_id' => '33'],
            ['id' => 209, "name" => 'Pitrufquén', 'province_id' => '33'],
            ['id' => 210, "name" => 'Pucón', 'province_id' => '33'],
            ['id' => 211, "name" => 'Saavedra', 'province_id' => '33'],
            ['id' => 212, "name" => 'Teodoro Schmidt', 'province_id' => '33'],
            ['id' => 213, "name" => 'Toltén', 'province_id' => '33'],
            ['id' => 214, "name" => 'Vilcún', 'province_id' => '33'],
            ['id' => 215, "name" => 'Villarrica', 'province_id' => '33'],
            ['id' => 216, "name" => 'Cholchol', 'province_id' => '33'],
            ['id' => 217, "name" => 'Angol', 'province_id' => '34'],
            ['id' => 218, "name" => 'Collipulli', 'province_id' => '34'],
            ['id' => 219, "name" => 'Curacautín', 'province_id' => '34'],
            ['id' => 220, "name" => 'Ercilla', 'province_id' => '34'],
            ['id' => 221, "name" => 'Lonquimay', 'province_id' => '34'],
            ['id' => 222, "name" => 'Los Sauces', 'province_id' => '34'],
            ['id' => 223, "name" => 'Lumaco', 'province_id' => '34'],
            ['id' => 224, "name" => 'Purén', 'province_id' => '34'],
            ['id' => 225, "name" => 'Renaico', 'province_id' => '34'],
            ['id' => 226, "name" => 'Traiguén', 'province_id' => '34'],
            ['id' => 227, "name" => 'Victoria', 'province_id' => '34'],
            ['id' => 228, "name" => 'Puerto Montt', 'province_id' => '37'],
            ['id' => 229, "name" => 'Calbuco', 'province_id' => '37'],
            ['id' => 230, "name" => 'Cochamó', 'province_id' => '37'],
            ['id' => 231, "name" => 'Fresia', 'province_id' => '37'],
            ['id' => 232, "name" => 'Frutillar', 'province_id' => '37'],
            ['id' => 233, "name" => 'Los Muermos', 'province_id' => '37'],
            ['id' => 234, "name" => 'Llanquihue', 'province_id' => '37'],
            ['id' => 235, "name" => 'Maullín', 'province_id' => '37'],
            ['id' => 236, "name" => 'Puerto Varas', 'province_id' => '37'],
            ['id' => 237, "name" => 'Castro', 'province_id' => '38'],
            ['id' => 238, "name" => 'Ancud', 'province_id' => '38'],
            ['id' => 239, "name" => 'Chonchi', 'province_id' => '38'],
            ['id' => 240, "name" => 'Curaco de Vélez', 'province_id' => '38'],
            ['id' => 241, "name" => 'Dalcahue', 'province_id' => '38'],
            ['id' => 242, "name" => 'Puqueldón', 'province_id' => '38'],
            ['id' => 243, "name" => 'Queilén', 'province_id' => '38'],
            ['id' => 244, "name" => 'Quellón', 'province_id' => '38'],
            ['id' => 245, "name" => 'Quemchi', 'province_id' => '38'],
            ['id' => 246, "name" => 'Quinchao', 'province_id' => '38'],
            ['id' => 247, "name" => 'Osorno', 'province_id' => '39'],
            ['id' => 248, "name" => 'Puerto Octay', 'province_id' => '39'],
            ['id' => 249, "name" => 'Purranque', 'province_id' => '39'],
            ['id' => 250, "name" => 'Puyehue', 'province_id' => '39'],
            ['id' => 251, "name" => 'Río Negro', 'province_id' => '39'],
            ['id' => 252, "name" => 'San Juan de la Costa', 'province_id' => '39'],
            ['id' => 253, "name" => 'San Pablo', 'province_id' => '39'],
            ['id' => 254, "name" => 'Chaitén', 'province_id' => '40'],
            ['id' => 255, "name" => 'Futaleufú', 'province_id' => '40'],
            ['id' => 256, "name" => 'Hualaihué', 'province_id' => '40'],
            ['id' => 257, "name" => 'Palena', 'province_id' => '40'],
            ['id' => 258, "name" => 'Coyhaique', 'province_id' => '41'],
            ['id' => 259, "name" => 'Lago Verde', 'province_id' => '41'],
            ['id' => 260, "name" => 'Aysén', 'province_id' => '42'],
            ['id' => 261, "name" => 'Cisnes', 'province_id' => '42'],
            ['id' => 262, "name" => 'Guaitecas', 'province_id' => '42'],
            ['id' => 263, "name" => 'Cochrane', 'province_id' => '43'],
            ['id' => 264, "name" => "O'Higgins", 'province_id' => '43'],
            ['id' => 265, "name" => 'Tortel', 'province_id' => '43'],
            ['id' => 266, "name" => 'Chile Chico', 'province_id' => '44'],
            ['id' => 267, "name" => 'Río Ibáñez', 'province_id' => '44'],
            ['id' => 268, "name" => 'Punta Arenas', 'province_id' => '45'],
            ['id' => 269, "name" => 'Laguna Blanca', 'province_id' => '45'],
            ['id' => 270, "name" => 'Río Verde', 'province_id' => '45'],
            ['id' => 271, "name" => 'San Gregorio', 'province_id' => '45'],
            ['id' => 272, "name" => 'Cabo de Hornos', 'province_id' => '46'],
            ['id' => 273, "name" => 'Antártica', 'province_id' => '46'],
            ['id' => 274, "name" => 'Porvenir', 'province_id' => '47'],
            ['id' => 275, "name" => 'Primavera', 'province_id' => '47'],
            ['id' => 276, "name" => 'Timaukel', 'province_id' => '47'],
            ['id' => 277, "name" => 'Natales', 'province_id' => '48'],
            ['id' => 278, "name" => 'Torres del Paine', 'province_id' => '48'],
            ['id' => 279, "name" => 'Santiago', 'province_id' => '49'],
            ['id' => 280, "name" => 'Cerrillos', 'province_id' => '49'],
            ['id' => 281, "name" => 'Cerro Navia', 'province_id' => '49'],
            ['id' => 282, "name" => 'Conchalí', 'province_id' => '49'],
            ['id' => 283, "name" => 'El Bosque', 'province_id' => '49'],
            ['id' => 284, "name" => 'Estación Central', 'province_id' => '49'],
            ['id' => 285, "name" => 'Huechuraba', 'province_id' => '49'],
            ['id' => 286, "name" => 'Independencia', 'province_id' => '49'],
            ['id' => 287, "name" => 'La Cisterna', 'province_id' => '49'],
            ['id' => 288, "name" => 'La Florida', 'province_id' => '49'],
            ['id' => 289, "name" => 'La Granja', 'province_id' => '49'],
            ['id' => 290, "name" => 'La Pintana', 'province_id' => '49'],
            ['id' => 291, "name" => 'La Reina', 'province_id' => '49'],
            ['id' => 292, "name" => 'Las Condes', 'province_id' => '49'],
            ['id' => 293, "name" => 'Lo Barnechea', 'province_id' => '49'],
            ['id' => 294, "name" => 'Lo Espejo', 'province_id' => '49'],
            ['id' => 295, "name" => 'Lo Prado', 'province_id' => '49'],
            ['id' => 296, "name" => 'Macul', 'province_id' => '49'],
            ['id' => 297, "name" => 'Maipú', 'province_id' => '49'],
            ['id' => 298, "name" => 'Ñuñoa', 'province_id' => '49'],
            ['id' => 299, "name" => 'Pedro Aguirre Cerda', 'province_id' => '49'],
            ['id' => 300, "name" => 'Peñalolén', 'province_id' => '49'],
            ['id' => 301, "name" => 'Providencia', 'province_id' => '49'],
            ['id' => 302, "name" => 'Pudahuel', 'province_id' => '49'],
            ['id' => 303, "name" => 'Quilicura', 'province_id' => '49'],
            ['id' => 304, "name" => 'Quinta Normal', 'province_id' => '49'],
            ['id' => 305, "name" => 'Recoleta', 'province_id' => '49'],
            ['id' => 306, "name" => 'Renca', 'province_id' => '49'],
            ['id' => 307, "name" => 'San Joaquín', 'province_id' => '49'],
            ['id' => 308, "name" => 'San Miguel', 'province_id' => '49'],
            ['id' => 309, "name" => 'San Ramón', 'province_id' => '49'],
            ['id' => 310, "name" => 'Vitacura', 'province_id' => '49'],
            ['id' => 311, "name" => 'Puente Alto', 'province_id' => '50'],
            ['id' => 312, "name" => 'Pirque', 'province_id' => '50'],
            ['id' => 313, "name" => 'San José de Maipo', 'province_id' => '50'],
            ['id' => 314, "name" => 'Colina', 'province_id' => '51'],
            ['id' => 315, "name" => 'Lampa', 'province_id' => '51'],
            ['id' => 316, "name" => 'Tiltil', 'province_id' => '51'],
            ['id' => 317, "name" => 'San Bernardo', 'province_id' => '52'],
            ['id' => 318, "name" => 'Buin', 'province_id' => '52'],
            ['id' => 319, "name" => 'Calera de Tango', 'province_id' => '52'],
            ['id' => 320, "name" => 'Paine', 'province_id' => '52'],
            ['id' => 321, "name" => 'Melipilla', 'province_id' => '53'],
            ['id' => 322, "name" => 'Alhué', 'province_id' => '53'],
            ['id' => 323, "name" => 'Curacaví', 'province_id' => '53'],
            ['id' => 324, "name" => 'María Pinto', 'province_id' => '53'],
            ['id' => 325, "name" => 'San Pedro', 'province_id' => '53'],
            ['id' => 326, "name" => 'Talagante', 'province_id' => '54'],
            ['id' => 327, "name" => 'El Monte', 'province_id' => '54'],
            ['id' => 328, "name" => 'Isla de Maipo', 'province_id' => '54'],
            ['id' => 329, "name" => 'Padre Hurtado', 'province_id' => '54'],
            ['id' => 330, "name" => 'Peñaflor', 'province_id' => '54'],
            ['id' => 331, "name" => 'Valdivia', 'province_id' => '35'],
            ['id' => 332, "name" => 'Corral', 'province_id' => '35'],
            ['id' => 333, "name" => 'Lanco', 'province_id' => '35'],
            ['id' => 334, "name" => 'Los Lagos', 'province_id' => '35'],
            ['id' => 335, "name" => 'Máfil', 'province_id' => '35'],
            ['id' => 336, "name" => 'Mariquina', 'province_id' => '35'],
            ['id' => 337, "name" => 'Paillaco', 'province_id' => '35'],
            ['id' => 338, "name" => 'Panguipulli', 'province_id' => '35'],
            ['id' => 339, "name" => 'La Unión', 'province_id' => '36'],
            ['id' => 340, "name" => 'Futrono', 'province_id' => '36'],
            ['id' => 341, "name" => 'Lago Ranco', 'province_id' => '36'],
            ['id' => 342, "name" => 'Río Bueno', 'province_id' => '36'],
            ['id' => 343, "name" => 'Arica', 'province_id' => '1'],
            ['id' => 344, "name" => 'Camarones', 'province_id' => '1'],
            ['id' => 345, "name" => 'Putre', 'province_id' => '2'],
            ['id' => 346, "name" => 'General Lagos', 'province_id' => '2'],
      
          ]);
    }
}
